apiVersion: v1
kind: Service
metadata:
  name: "{{ cookiecutter.slug }}-service"
  namespace: api
spec:
  selector:
    app: "{{ cookiecutter.slug }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP